module.exports = {
  FIELDS_MAP: Symbol.for('FIELDS_MAP'),
  FIELD_MARKER: Symbol.for('FIELD_SPECIFICATION_MARKER'),
  ENTITY_CORE_KEY: Symbol.for('ENTITY_CORE_KEY'),
  ENTITY_INJECTION_ID: Symbol.for('ENTITY_INJECTION_ID'),
  MODEL_INJECTION_ID: Symbol.for('MODEL_INJECTION_ID'),
  REPOSYTORY_INJECTION_ID: Symbol.for('REPOSYTORY_INJECTION_ID'),
  SERVICE_INJECTION_ID: Symbol.for('SERVICE_INJECTION_ID'),
};
